module(name = "mdtensor")

bazel_dep(name = "rules_cc", version = "0.2.17")

# conditional dependencies for mdtensor
bazel_dep(name = "eigen", version = "5.0.1.bcr.2")

# only needed for testing and benchmarking
bazel_dep(name = "googletest", version = "1.17.0")
bazel_dep(name = "google_benchmark", version = "1.9.5")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

# mdspan // TODO: Remove when C++23 mdspan supports.
git_repository(
    name = "mdspan",
    remote = "https://github.com/kokkos/mdspan.git",
    commit = "9ceface91483775a6c74d06ebf717bbb2768452f", # commit for mdspan-0.6.0
    build_file_content =
"""
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "mdspan",
    hdrs = glob(["include/**/*"]),
    srcs = [],
    includes = ["include/"],
    defines = ["MDSPAN_USE_BRACKET_OPERATOR=0"], # NOTE: For C++20 compatibility
    visibility = ["//visibility:public"],
)
"""
)
