# load("@rules_cc//cc:defs.bzl", "cc_binary")

# cc_binary(
#     name = "main",
#     srcs = [
#         "main.cpp"
#     ],
#     copts = [
#         "-O3",
#         "-funroll-loops",
#         "-march=native",
#         "-fopenmp",
#         "-foffload=nvptx-none",
#     ],
#     linkopts = [
#         "-fopenmp",
#         "-B/opt/gcc-13/bin",
#         "-foffload=nvptx-none",
#         "-lgomp",
#     ],
#     deps = [
#         "//benchmarks/common:benchmarking",
#     ],
# )
