load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "main",
    srcs = [
        "main.cpp"
    ],
    copts = [
        "-O3",
        "-funroll-loops",
        "-march=native",
        "-fopenmp",
    ],
    linkopts = [
        "-fopenmp",
    ],
    deps = [
        "//benchmarks/common:benchmarking",
    ],
)
